# This is a basic workflow to help you get started with Actions

name: Django_project

on: [push]
  

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.7

      - name: Install dependies
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          cd api_yamdb/
          pip install -r requirements.txt
      
      - name: Test with Flake8 and pytest
        run: |
          python -m flake8
