# This is a basic workflow to help you get started with Actions

name: Django_project

on: [push]
  

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.7

      - name: Install dependies
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          cd api_yamdb/
          pip install -r requirements.txt
      
      - name: Test with Flake8 and pytest
        run: |
          python -m flake8

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /api_yamdb
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:api_yamdb"
          push: true
          tags: sayyod1981/infra:latest
  
